apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
spec:
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config-service
        image: jaesuk95/portfolio-config-service:0.0.1
        imagePullPolicy: Always
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        env:
          - name: SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME
            valueFrom:
              name: mysecret
              key: git-username
          - name: SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD
            valueFrom:
              name: mysecret
              key: git-password
          - name: SPRING_RABBITMQ_HOST
            # value: "10.98.240.176"
            value: "rabbitmq"
        ports:
        - containerPort: 8888
