apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-service
spec:
  selector:
    matchLabels:
      app: apigateway-service
  template:
    metadata:
      labels:
        app: apigateway-service
    spec:
      containers:
      - name: apigateway-service
        image: jaesuk95/portfolio-apigateway-service:0.0.2
        imagePullPolicy: Always
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        env:
          # - name: SPRING_PROFILES_ACTIVE
          #   value: "dev"
          - name: EUREKA_CLIENT_ENABLED
            value: "true"
          - name: EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE
            value: http://discovery-service:8761/eureka
          - name: SPRING_RABBITMQ_HOST
            value: "rabbitmq"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://config-service:8888"
        ports:
        - containerPort: 8000

          # - name: EUREAK_INSTANCE_HOSTNAME
          #   value: "http://discovery-service:8761"