apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: jaesuk95/portfolio-order-service:0.0.2
        imagePullPolicy: Always
        env:
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://config-service:8888"
          - name: EUREKA_CLIENT_ENABLED
            value: "true"
          - name: EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE
            value: "http://discovery-service:8761/eureka"
          - name: SPRING_RABBITMQ_HOST
            value: "rabbitmq"
          - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
            value: "http://zipkin:9411/api/v2/spans"
        ports:
        - containerPort: 8080
