apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
      containers:
      - name: user
        image: jaesuk95/portfolio-user-service:0.0.10
        imagePullPolicy: Always
        env:
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://config-service:8888"
            
          - name: EUREKA_CLIENT_ENABLED
            value: "true"

          - name: EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE
            value: "http://discovery-service:8761/eureka"

          - name: SPRING_RABBITMQ_HOST
            value: "rabbitmq"
            
        ports:
        - containerPort: 8080