apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
      containers:
      - name: user-service
        image: jaesuk95/portfolio-user-service:0.0.4
        imagePullPolicy: Always
        env:
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://config-service:8888"
          - name: EUREKA_CLIENT_ENABLED
            value: "true"
          - name: EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE
            value: "http://discovery-service:8761/eureka"
          - name: APP_USER-SERVICE-URL
            value: "http://user-service/user-service"
          - name: SPRING_RABBITMQ_HOST
            value: "rabbitmq"
          - name: APP_ORDER-SERVICE-URL
            value: "http://order-service/order-service"
        ports:
        - containerPort: 8080