apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
      containers:
      - name: user
        image: jaesuk95/portfolio-user-service:0.0.9
        imagePullPolicy: Always
        env:
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://config-service:8888"
            
          - name: EUREKA_CLIENT_ENABLED
            value: "true"

          - name: EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE
            value: "http://discovery-service:8761/eureka"

          - name: SPRING_RABBITMQ_HOST
            value: "rabbitmq"

          - name: APP_ORDERURL
            # value: "http://10.98.37.63:80"
            value: "order-service"

          - name: APP_USERURL
            # value: "http://10.111.129.100:80"
            value: "user-service"

          # - name: APP_PAYMENTURL
          #   value: "http://payment/payment-service"
        ports:
        - containerPort: 8080