server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jaesuk95/git-cloud.git
          default-label: master
#          uri: https://github.com/jaesuk95/inflearn-spring-cloud-config.git
#          private ? ??
#          username: [username]
#          password: [password]

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
